#!/usr/bin/env bash

# This is a BeeDeeM external task script aims at making 
# FASTA file out of a BLAST bank.
#
# This script is called by run_blastcmd.sh
#
# Such a BeeDeeM script is called by the task engine and
# with arguments as defined in: 
# ./scheduler/common.sh->handleBDMArgs() function

echo "Making FASTA file from BLAST bank"

# ========================================================================================
# Section: include API
S_NAME=$(realpath "$0")
script_dir=$(dirname "$S_NAME")
. $script_dir/scheduler/common.sh

# ========================================================================================
# Section: handle arguemnts
# Function call setting BDMC_xxx variables from cmdline arguments
handleBDMArgs $@
RET_CODE=$?
[ ! $RET_CODE -eq 0 ] && errorMsg "Wrong or missing arguments" && exit $RET_CODE
#Note: BDMC_PLATFORM is set to generic is not defined, so not need to test empty var
. $script_dir/scheduler/env_${BDMC_PLATFORM}.sh

# ========================================================================================
# Section: do business
# Run tool
SOFT_NAME=blast
SOFT_VER=2.12.0
activateEnv "$SOFT_NAME" "$SOFT_VER"
cd $BDMC_INST_DIR
if [ -e "${BDMC_BANK_NAME}00" ]; then
  echo "FASTA: ${BDMC_BANK_NAME}00: already exists, exit"
  exit 0
fi
CMD="blastdbcmd -entry all -db ${BDMC_BANK_NAME}M -out ${BDMC_BANK_NAME}00.tmp"
echo $CMD
eval $CMD
RET_CODE=$?
if [ $RET_CODE -eq 0 ]; then
  mv ${BDMC_BANK_NAME}00.tmp ${BDMC_BANK_NAME}00
  chmod 644 ${BDMC_BANK_NAME}00
fi
deActivateEnv "$SOFT_NAME" "$SOFT_VER"
exit $RET_CODE

