language: java

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jdk_switcher use oraclejdk8; fi

# BeeDeeM uses graphical layers from Java/Swing. So, to enable
# GUI app to run on Travis CI, we have to add these lines:
# (according to https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI)
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "export DISPLAY=:99.0"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "sh -e /etc/init.d/xvfb start"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi # give xvfb some time to start

script:
  ant ut

after_failure:
  if [ -f /home/travis/build/pgdurand/BeeDeeM/distrib/tests-result/TEST-test.unit.AllTests.txt ]; then cat /home/travis/build/pgdurand/BeeDeeM/distrib/tests-result/TEST-test.unit.AllTests.txt; fi

