language: java
jdk:
  - oraclejdk8
script:
  ant ut
after_failure:
  if [ -f /home/travis/build/pgdurand/BeeDeeM/distrib/tests-result/TEST-test.unit.AllTests.txt ]; then cat /home/travis/build/pgdurand/BeeDeeM/distrib/tests-result/TEST-test.unit.AllTests.txt; fi

