{% set name = "beedeem" %}
{% set version = "5.0.0" %}
{% set sha256 = "395b8e56919e2f20715bb636d3ccaa1a4c98302547836c768b3189f131902b58" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../distrib/beedeem-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: generic

requirements:
  run:
     - java-jdk=8

about:
  home: https://github.com/pgdurand/BeeDeeM
  license: GNU Affero General Public 3.0
  license_file: 
    - license/LICENSE.txt
    - license/NOTICE.txt
  summary: BeeDeeM is a general purpose Bioinformatics Databank Manager.

