{% set name = "beedeem" %}
{% set version = "6.0.0" %}
{% set sha256 = "22e671ad08dd21a79b176cd5753cbe096df90e5458f1c850159268705a8e5b0b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../distrib/beedeem-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0

requirements:
  run:
    - openjdk =21
      # BeeDeeM comes with blast 2.17.0 binaries: makeblastdb and blastdbcmd
      # It seems they work on conda env withou declaring any additional
      # librairies. In case of troubleshooting, please refer to bioconda
      # recipe: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/blast/meta.yaml 

about:
  home: https://github.com/pgdurand/BeeDeeM
  license: GNU Affero General Public 3.0
  license_file: 
    - license/LICENSE.txt
    - license/NOTICE.txt
  summary: BeeDeeM is a general purpose Bioinformatics Databank Manager.

extra:
  identifiers:
    - biotools:beedeem
  recipe-maintainers:
    - pgdurand
