{% set name = "beedeem" %}
{% set version = "4.7.6" %}
{% set sha256 = "62e98492b40848ed59af3f80d9c332f91492c668e3f6bf021407511d89dc94a2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
#   path: ../distrib/beedeem-{{ version }}.tar.gz
  url: https://github.com/pgdurand/BeeDeeM/releases/download/v{{ version }}/beedeem-{{ version }}-distrib.zip
  sha256: '{{ sha256 }}'

build:
  noarch: generic

requirements:
  run:
     - java-jdk=8

about:
  home: https://github.com/pgdurand/BeeDeeM
  license: GNU Affero General Public 3.0
  license_file: 
    - license/LICENSE.txt
    - license/NOTICE.txt
  summary: BeeDeeM is a general purpose Bioinformatics Databank Manager.

