# #############################################################################
# Recipe to build a Singularity image for BeeDeeM software
# This image relies upon https://github.com/platten/alpine-oracle-jre8-docker
# #############################################################################

Bootstrap : docker
From: platten/alpine-oracle-jre8-docker

%post
	BDM_VERSION=4.7.2
	apk update
        # libbz2 libidn are required by blast tools included in BeeDeeM.
        # libxext libxrender libxtst libxi are required by Bioinformatics-Core-API included 
        #    in BeeDeeM and BeeDeeM-Tools.
        # bash is required when running this image by Nextflow pipelines.
        # wget is required to install some banks (e.g. GeneOntology).
        apk add --no-cache libbz2 libidn bash wget libxext libxrender libxtst libxi

	# Get BeeDeeM from latest release
	mkdir -p /opt/beedeem/tmp-install
	cd /opt/beedeem/tmp-install
	wget https://github.com/pgdurand/BeeDeeM/releases/download/v${BDM_VERSION}/beedeem-${BDM_VERSION}-distrib.zip
	
	# Unpack BeeDeeM to /opt/beedeem
	unzip beedeem-${BDM_VERSION}-distrib.zip
	tar -zxf beedeem-${BDM_VERSION}.tar.gz -C /opt/beedeem
	cd ..
	rm -rf tmp-install
	
	# Do a little configuration
	cp scripts/*.sh .
        sed -i 's/@KL_WORKING_DIR@/\/beedeem-wk/g' *.sh
        sed -i 's/@JAVA_ARGS@/-Xms128M -Xmx2048M -Djava.io.tmpdir=\/beedeem-wk -DKL_LOG_TYPE=console/g' *.sh
	cp scripts/dbms.config conf
	sed -i 's/@BIOBASE_ROOTDIR@/\/beedeem-db/g' conf/dbms.config
	chmod +x *.sh
	chmod +x /opt/beedeem/external/bin/linux/*
	chmod +x /opt/beedeem/conf/scripts/*.sh
	cd /opt/beedeem/external/bin && rm -rf macos windows

	BDMT_VERSION=2.1.0
	cd /opt
	mkdir beedeem-tools
	cd beedeem-tools
	wget https://github.com/ifremer-bioinformatics/BeeDeeM-Tools/releases/download/v${BDMT_VERSION}/beedeem-tools-${BDMT_VERSION}.tar.gz
	gunzip beedeem-tools-${BDMT_VERSION}.tar.gz
	tar -xf beedeem-tools-${BDMT_VERSION}.tar
	rm beedeem-tools-${BDMT_VERSION}.tar
	chmod +x *.sh


%environment
	export PATH="/opt/beedeem:/opt/beedeem-tools:$PATH"
