# #############################################################################
# Recipe to build a Singularity image for BeeDeeM software
#
# Build image from official zipball available at:
#   https://github.com/pgdurand/BeeDeeM/releases/download/v${BDM_VERSION}/beedeem-${BDM_VERSION}-distrib.zip
# #############################################################################

Bootstrap : docker
From: debian:11-slim

%post
	BDM_VERSION=5.0.2
	BDMT_VERSION=2.1.2
	
	# software-properties-common required to install Java Runtime
	# libbz2 libidn are required by blast tools included in BeeDeeM.
	# libxext libxrender libxtst libxi are required by Bioinformatics-Core-API included 
	#    in BeeDeeM and BeeDeeM-Tools.
	# bash is required when running this image by Nextflow pipelines.
	# wget is required to install some banks (e.g. GeneOntology).
	# procps (ps command) is required by Nextflow. 
	apt-get -y update
	apt-get -y install gawk openssh-client software-properties-common bzip2 libidn11 bash wget libxext6 libxrender1 libxtst6 libxi6 unzip procps
	
	# Java
	# See https://www.oracle.com/java/technologies/downloads/#java17
        cd /opt
        wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb
	apt install -y /opt/jdk-17_linux-x64_bin.deb
	rm jdk-17_linux-x64_bin.deb
	
	# Get BeeDeeM from latest local release
        mkdir -p /opt/beedeem/tmp-install
        cd /opt/beedeem/tmp-install
        wget https://github.com/pgdurand/BeeDeeM/releases/download/v${BDM_VERSION}/beedeem-${BDM_VERSION}-distrib.zip
	
	# Unpack BeeDeeM to /opt/beedeem
	unzip beedeem-${BDM_VERSION}-distrib.zip
	tar -zxf beedeem-${BDM_VERSION}.tar.gz -C /opt/beedeem
	cd ..
	rm -rf tmp-install
	
	# Do a little configuration
	cp scripts/bdm.sh ./bdm
	sed -i 's/@KL_WORKING_DIR@/\/beedeem-wk/g' bdm
	sed -i 's/@JAVA_ARGS@/-Xms128M -Xmx2048M -Djava.io.tmpdir=\$KL_WORKING_DIR -DKL_LOG_TYPE=console/g' bdm
	cp scripts/dbms.config conf
	sed -i 's/@BIOBASE_ROOTDIR@/\/beedeem-db/g' conf/dbms.config
	chmod +x bdm
	chmod +x /opt/beedeem/external/bin/linux/*
	chmod +x /opt/beedeem/conf/scripts/*.sh
	chmod +x /opt/beedeem/conf/scripts/scheduler/*.sh
	cd /opt/beedeem/external/bin && rm -rf macos windows

	# Get BeeDeeM-Tools from latest local release
	cd /opt
	mkdir beedeem-tools
	cd beedeem-tools
	wget https://gitlab.ifremer.fr/api/v4/projects/91/packages/generic/BeeDeeM-Tools/${BDMT_VERSION}/beedeem-tools-${BDMT_VERSION}.tar.gz
	gunzip beedeem-tools-${BDMT_VERSION}.tar.gz
	tar -xf beedeem-tools-${BDMT_VERSION}.tar
	rm beedeem-tools-${BDMT_VERSION}.tar
	chmod +x *.sh

%environment
	export PATH="/opt/beedeem:/opt/beedeem-tools:$PATH"
	

